
enyo.depends(
  "source/WordPress.js",
  "source/SourceList.js",
  "source/AccountListItem.js",
  "source/GlobalListItem.js",
  "source/Comments.js",
  "source/CommentList.js",
  "source/CommentView.js",
  "source/Posts.js",
  "source/PostList.js",
  "source/PostView.js",
  "source/PostPreviewView.js",
  "source/AccountSetup.js",
  'source/Accounts.js',
  "css/WordPress.css",
  "source/BlogDiscover.js",
  "lib/md5.js",
  "lib/XMLRPCService.js",
  "lib/WordPressService.js",
  "lib/SimpleHtmlParser.js",
  "Canvas.js"
);